### ISSUE TITLE
Bump aws provider version or allow 5+

### ISSUE THREAD

**Issue by rgarrigue** [antimetal/terraform-aws-antimetal#2]
You've pinned this to 4.16, but we're using 5+, and it conflict in our wider module

**Comment by brnovais** [comment]
Thank you for pointing that out @rgarrigue. On `v1.0.2` we soften the version constraint, so it should work with newer versions. I just tested `terraform init` with a clean repo and Terraform downloaded `hashicorp/aws v5.11.0`.
